# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# reset all id sequences to 1
ActiveRecord::Base.connection.tables.each do |t|
    ActiveRecord::Base.connection.reset_pk_sequence!(t)
end

User.find_or_create_by(name: 'Ryan', username: 'Ryan X.', password: 'password', is_auth: true)
User.find_or_create_by(name: 'April', username: 'aprilsanchez', password: 'password', is_auth: true)
User.find_or_create_by(name: 'Laboni', username: 'Laboni', password: 'password', is_auth: true)
User.find_or_create_by(name: 'Wei-Yee', username: 'weigee', password: 'password', is_auth: true)
User.find_or_create_by(name: 'Saurav', username: 'sauravucsb', password: 'password', is_auth: true)
User.find_or_create_by(name: 'Mat', username: 'mateolithium', password: 'password', is_auth: true)

Location.find_or_create_by(name: "Isla Vista")
Location.find_or_create_by(name: "Santa Barbara")
Location.find_or_create_by(name: "Solvang")

Room.find_or_create_by(token: "ABCDE", name: "Manzanita Floor 1 Decision", location_id: 1)
Room.find_or_create_by(token: "EFGHI", name: "Take decision", location_id: 1)
Room.find_or_create_by(token: "IJKLM", name: "Food hangout", location_id: 1)
Room.find_or_create_by(token: "MNOPQ", name: "Let's party", location_id: 1)
Room.find_or_create_by(token: "QRSTU", name: "Where to go?", location_id: 1)
Room.find_or_create_by(token: "UVWXY", name: "Quick decision", location_id: 1)
Room.find_or_create_by(token: "BCDEF", name: "Room1", location_id: 1)
Room.find_or_create_by(token: "FGHIJ", name: "Room2", location_id: 1)
Room.find_or_create_by(token: "JKLMN", name: "Room3", location_id: 1)
Room.find_or_create_by(token: "NOPQR", name: "Room4", location_id: 1)


Room.find_or_create_by(token: "ABCDE1", name: "Manzanita Floor 1 Decision1", location_id: 1)
Room.find_or_create_by(token: "EFGHI1", name: "Take decision1", location_id: 1)
Room.find_or_create_by(token: "IJKLM1", name: "Food hangout1", location_id: 1)
Room.find_or_create_by(token: "MNOPQ1", name: "Let's party1", location_id: 1)
Room.find_or_create_by(token: "QRSTU1", name: "Where to go?1", location_id: 1)
Room.find_or_create_by(token: "UVWXY1", name: "Quick decision1", location_id: 1)
Room.find_or_create_by(token: "BCDEF1", name: "Room11", location_id: 1)
Room.find_or_create_by(token: "FGHIJ1", name: "Room21", location_id: 1)
Room.find_or_create_by(token: "JKLMN1", name: "Room31", location_id: 1)
Room.find_or_create_by(token: "NOPQR1", name: "Room41", location_id: 1)

Room.find_or_create_by(token: "ABCDE2", name: "Manzanita Floor 1 Decision2", location_id: 1)
Room.find_or_create_by(token: "EFGHI2", name: "Take decision2", location_id: 1)
Room.find_or_create_by(token: "IJKLM2", name: "Food hangout2", location_id: 1)
Room.find_or_create_by(token: "MNOPQ2", name: "Let's party2", location_id: 1)
Room.find_or_create_by(token: "QRSTU2", name: "Where to go?2", location_id: 1)
Room.find_or_create_by(token: "UVWXY2", name: "Quick decision2", location_id: 1)
Room.find_or_create_by(token: "BCDEF2", name: "Room12", location_id: 1)
Room.find_or_create_by(token: "FGHIJ2", name: "Room22", location_id: 1)
Room.find_or_create_by(token: "JKLMN2", name: "Room23", location_id: 1)
Room.find_or_create_by(token: "NOPQR2", name: "Room42", location_id: 1)

Room.find_or_create_by(token: "ABCDE3", name: "Manzanita Floor 1 Decision3", location_id: 1)
Room.find_or_create_by(token: "EFGHI3", name: "Take decision3", location_id: 1)
Room.find_or_create_by(token: "IJKLM3", name: "Food hangout3", location_id: 1)
Room.find_or_create_by(token: "MNOPQ3", name: "Let's party3", location_id: 1)
Room.find_or_create_by(token: "QRSTU3", name: "Where to go?3", location_id: 1)
Room.find_or_create_by(token: "UVWXY3", name: "Quick decision3", location_id: 1)
Room.find_or_create_by(token: "BCDEF3", name: "Room13", location_id: 1)
Room.find_or_create_by(token: "FGHIJ3", name: "Room23", location_id: 1)
Room.find_or_create_by(token: "JKLMN3", name: "Room33", location_id: 1)
Room.find_or_create_by(token: "NOPQR3", name: "Room43", location_id: 1)

Room.find_or_create_by(token: "ABCDE4", name: "Manzanita Floor 1 Decision4", location_id: 1)
Room.find_or_create_by(token: "EFGHI4", name: "Take decision4", location_id: 1)
Room.find_or_create_by(token: "IJKLM4", name: "Food hangout4", location_id: 1)
Room.find_or_create_by(token: "MNOPQ4", name: "Let's party4", location_id: 1)
Room.find_or_create_by(token: "QRSTU4", name: "Where to go?4", location_id: 1)
Room.find_or_create_by(token: "UVWXY4", name: "Quick decision4", location_id: 1)
Room.find_or_create_by(token: "BCDEF4", name: "Room14", location_id: 1)
Room.find_or_create_by(token: "FGHIJ4", name: "Room24", location_id: 1)
Room.find_or_create_by(token: "JKLMN4", name: "Room34", location_id: 1)
Room.find_or_create_by(token: "NOPQR4", name: "Room44", location_id: 1)

Member.find_or_create_by(room_id: 1, user_id: 1, is_host: false)
Member.find_or_create_by(room_id: 1, user_id: 2, is_host: false)
Member.find_or_create_by(room_id: 1, user_id: 3, votes:"7;8;9;10;11", is_host: true)
Member.find_or_create_by(room_id: 2, user_id: 1, is_host: true)
Member.find_or_create_by(room_id: 2, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 3, user_id: 3, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 3, user_id: 1, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 3, user_id: 2, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 4, user_id: 3, votes:"4;5;8;2", is_host: false)
Member.find_or_create_by(room_id: 4, user_id: 2, votes:"5;8;2", is_host: false)
Member.find_or_create_by(room_id: 4, user_id: 1, votes:"4;8;2", is_host: true)
Member.find_or_create_by(room_id: 4, user_id: 4, votes:"4;5;8", is_host: false)
Member.find_or_create_by(room_id: 4, user_id: 5,  is_host: false)
Member.find_or_create_by(room_id: 5, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 5, user_id: 4, votes:"1;2;14", is_host: false)
Member.find_or_create_by(room_id: 5, user_id: 2, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 5, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 6, user_id: 1, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 6, user_id: 2, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 6, user_id: 3, votes:"11;12;13;3;4;6;7", is_host: false)
Member.find_or_create_by(room_id: 6, user_id: 4, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 7, user_id: 3, votes:"1;2;3;5;6;7;8;9;10", is_host: false)
Member.find_or_create_by(room_id: 7, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 7, user_id: 2, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 7, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 8, user_id: 3, votes:"9;10;11;12;8;1;2", is_host: false)
Member.find_or_create_by(room_id: 8, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 8, user_id: 2, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 8, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 9, user_id: 3, votes:"7;5;1;6;9;10;14", is_host: false)
Member.find_or_create_by(room_id: 9, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 9, user_id: 2, votes:"1;2;3;10;14", is_host: true)
Member.find_or_create_by(room_id: 9, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 10, user_id: 3, votes:"1;2;3", is_host: true)
Member.find_or_create_by(room_id: 10, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 10, user_id: 2, votes:"1;2;3;14;11", is_host: false)
Member.find_or_create_by(room_id: 10, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 11, user_id: 3, is_host: true)
Member.find_or_create_by(room_id: 12, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 13, user_id: 3, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 14, user_id: 3, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 15, user_id: 3, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 16, user_id: 3, votes:"4;5;8;2", is_host: false)
Member.find_or_create_by(room_id: 17, user_id: 3, votes:"5;8;2", is_host: false)
Member.find_or_create_by(room_id: 18, user_id: 3, votes:"4;8;2", is_host: true)
Member.find_or_create_by(room_id: 19, user_id: 3, votes:"4;5;8", is_host: false)
Member.find_or_create_by(room_id: 20, user_id: 3,  is_host: false)
Member.find_or_create_by(room_id: 21, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 22, user_id: 3, votes:"1;2;14", is_host: false)
Member.find_or_create_by(room_id: 23, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 24, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 25, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 26, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 27, user_id: 3, votes:"11;12;13;3;4;6;7", is_host: false)
Member.find_or_create_by(room_id: 28, user_id: 3, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 29, user_id: 3, votes:"1;2;3;5;6;7;8;9;10", is_host: false)
Member.find_or_create_by(room_id: 30, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 31, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 32, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 33, user_id: 3, votes:"9;10;11;12;8;1;2", is_host: false)
Member.find_or_create_by(room_id: 34, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 35, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 36, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 37, user_id: 3, votes:"7;5;1;6;9;10;14", is_host: false)
Member.find_or_create_by(room_id: 38, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 39, user_id: 3, votes:"1;2;3;10;14", is_host: true)
Member.find_or_create_by(room_id: 40, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 41, user_id: 3, votes:"1;2;3", is_host: true)
Member.find_or_create_by(room_id: 42, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 43, user_id: 3, votes:"1;2;3;14;11", is_host: false)
Member.find_or_create_by(room_id: 44, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 45, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 46, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 47, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 48, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 49, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 50, user_id: 3, is_host: false)

Restaurant.find_or_create_by(name: "Deja Vu", location_id: 1, description: "Indian food")
Restaurant.find_or_create_by(name: "Freebirds", location_id: 1, description: "Burritos")
Restaurant.find_or_create_by(name: "Woodstock's Pizza", location_id: 1, description: "Pizza")
Restaurant.find_or_create_by(name: "South Coast Deli", location_id: 1, description: "Sandwiches")
Restaurant.find_or_create_by(name: "Naan Stop", location_id: 1, description: "Indian food")
Restaurant.find_or_create_by(name: "Hanna Kitchen", location_id: 1, description: "Asian fusion")
Restaurant.find_or_create_by(name: "The Habit", location_id: 1, description: "SB Burgers")
Restaurant.find_or_create_by(name: "Super Cuca's", location_id: 1, description: "Mexican Burgers")
Restaurant.find_or_create_by(name: "Buddha Bowls", location_id: 1, description: "Bread Bowls")
Restaurant.find_or_create_by(name: "Poke Ceviche", location_id: 1, description: "Poke and Wraps")
Restaurant.find_or_create_by(name: "Spudnuts", location_id: 1, description: "Donuts")
Restaurant.find_or_create_by(name: "Caje", location_id: 1, description: "Hip Coffee Shop")
Restaurant.find_or_create_by(name: "Lao Wang", location_id: 1, description: "Asian food")
Restaurant.find_or_create_by(name: "Shushiya", location_id: 1, description: "Shushi place")
