# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# reset all id sequences to 1
ActiveRecord::Base.connection.tables.each do |t|
    ActiveRecord::Base.connection.reset_pk_sequence!(t)
end

User.find_or_create_by(name: 'Ryan', username: 'Ryan X.', password: 'password', is_auth: true)
User.find_or_create_by(name: 'April', username: 'aprilsanchez', password: 'password', is_auth: true)
User.find_or_create_by(name: 'Laboni', username: 'Laboni', password: 'password', is_auth: true)
User.find_or_create_by(name: 'Wei-Yee', username: 'weigee', password: 'password', is_auth: true)
User.find_or_create_by(name: 'Saurav', username: 'sauravucsb', password: 'password', is_auth: true)
User.find_or_create_by(name: 'Mat', username: 'mateolithium', password: 'password', is_auth: true)

Location.find_or_create_by(name: "Isla Vista")
Location.find_or_create_by(name: "Santa Barbara")
Location.find_or_create_by(name: "Solvang")

Room.find_or_create_by(token: "ABCDE", name: "Manzanita Floor 1 Decision", location_id: 1)
Room.find_or_create_by(token: "EFGHI", name: "Take decision", location_id: 1)
Room.find_or_create_by(token: "IJKLM", name: "Food hangout", location_id: 1)
Room.find_or_create_by(token: "MNOPQ", name: "Let's party", location_id: 1)
Room.find_or_create_by(token: "QRSTU", name: "Where to go?", location_id: 1)
Room.find_or_create_by(token: "UVWXY", name: "Quick decision", location_id: 1)
Room.find_or_create_by(token: "BCDEF", name: "Room1", location_id: 1)
Room.find_or_create_by(token: "FGHIJ", name: "Room2", location_id: 1)
Room.find_or_create_by(token: "JKLMN", name: "Room3", location_id: 1)
Room.find_or_create_by(token: "NOPQR", name: "Room4", location_id: 1)
Room.find_or_create_by(token: "ABCDE1", name: "Manzanita Floor 1 Decision1", location_id: 1)
Room.find_or_create_by(token: "EFGHI1", name: "Take decision1", location_id: 1)
Room.find_or_create_by(token: "IJKLM1", name: "Food hangout1", location_id: 1)
Room.find_or_create_by(token: "MNOPQ1", name: "Let's party1", location_id: 1)
Room.find_or_create_by(token: "QRSTU1", name: "Where to go?1", location_id: 1)
Room.find_or_create_by(token: "UVWXY1", name: "Quick decision1", location_id: 1)
Room.find_or_create_by(token: "BCDEF1", name: "Room11", location_id: 1)
Room.find_or_create_by(token: "FGHIJ1", name: "Room21", location_id: 1)
Room.find_or_create_by(token: "JKLMN1", name: "Room31", location_id: 1)
Room.find_or_create_by(token: "NOPQR1", name: "Room41", location_id: 1)
Room.find_or_create_by(token: "ABCDE2", name: "Manzanita Floor 1 Decision2", location_id: 1)
Room.find_or_create_by(token: "EFGHI2", name: "Take decision2", location_id: 1)
Room.find_or_create_by(token: "IJKLM2", name: "Food hangout2", location_id: 1)
Room.find_or_create_by(token: "MNOPQ2", name: "Let's party2", location_id: 1)
Room.find_or_create_by(token: "QRSTU2", name: "Where to go?2", location_id: 1)
Room.find_or_create_by(token: "UVWXY2", name: "Quick decision2", location_id: 1)
Room.find_or_create_by(token: "BCDEF2", name: "Room12", location_id: 1)
Room.find_or_create_by(token: "FGHIJ2", name: "Room22", location_id: 1)
Room.find_or_create_by(token: "JKLMN2", name: "Room23", location_id: 1)
Room.find_or_create_by(token: "NOPQR2", name: "Room42", location_id: 1)
Room.find_or_create_by(token: "ABCDE3", name: "Manzanita Floor 1 Decision3", location_id: 1)
Room.find_or_create_by(token: "EFGHI3", name: "Take decision3", location_id: 1)
Room.find_or_create_by(token: "IJKLM3", name: "Food hangout3", location_id: 1)
Room.find_or_create_by(token: "MNOPQ3", name: "Let's party3", location_id: 1)
Room.find_or_create_by(token: "QRSTU3", name: "Where to go?3", location_id: 1)
Room.find_or_create_by(token: "UVWXY3", name: "Quick decision3", location_id: 1)
Room.find_or_create_by(token: "BCDEF3", name: "Room13", location_id: 1)
Room.find_or_create_by(token: "FGHIJ3", name: "Room23", location_id: 1)
Room.find_or_create_by(token: "JKLMN3", name: "Room33", location_id: 1)
Room.find_or_create_by(token: "NOPQR3", name: "Room43", location_id: 1)
Room.find_or_create_by(token: "ABCDE4", name: "Manzanita Floor 1 Decision4", location_id: 1)
Room.find_or_create_by(token: "EFGHI4", name: "Take decision4", location_id: 1)
Room.find_or_create_by(token: "IJKLM4", name: "Food hangout4", location_id: 1)
Room.find_or_create_by(token: "MNOPQ4", name: "Let's party4", location_id: 1)
Room.find_or_create_by(token: "QRSTU4", name: "Where to go?4", location_id: 1)
Room.find_or_create_by(token: "UVWXY4", name: "Quick decision4", location_id: 1)
Room.find_or_create_by(token: "BCDEF4", name: "Room14", location_id: 1)
Room.find_or_create_by(token: "FGHIJ4", name: "Room24", location_id: 1)
Room.find_or_create_by(token: "JKLMN4", name: "Room34", location_id: 1)
Room.find_or_create_by(token: "NOPQR4", name: "Room44", location_id: 1)



Room.find_or_create_by(token: "ABCDE5", name: "Manzanita Floor 1 Decision5", location_id: 1)
Room.find_or_create_by(token: "EFGHI5", name: "Take decision5", location_id: 1)
Room.find_or_create_by(token: "IJKLM5", name: "Food hangout5", location_id: 1)
Room.find_or_create_by(token: "MNOPQ5", name: "Let's party5", location_id: 1)
Room.find_or_create_by(token: "QRSTU5", name: "Where to go?5", location_id: 1)
Room.find_or_create_by(token: "UVWXY5", name: "Quick decision5", location_id: 1)
Room.find_or_create_by(token: "BCDEF5", name: "Room15", location_id: 1)
Room.find_or_create_by(token: "FGHIJ5", name: "Room2", location_id: 1)
Room.find_or_create_by(token: "JKLMN5", name: "Room3", location_id: 1)
Room.find_or_create_by(token: "NOPQR5", name: "Room4", location_id: 1)
Room.find_or_create_by(token: "ABCDE15", name: "Manzanita Floor 1 Decision15", location_id: 1)
Room.find_or_create_by(token: "EFGHI15", name: "Take decision15", location_id: 1)
Room.find_or_create_by(token: "IJKLM15", name: "Food hangout15", location_id: 1)
Room.find_or_create_by(token: "MNOPQ15", name: "Let's party15", location_id: 1)
Room.find_or_create_by(token: "QRSTU15", name: "Where to go?15", location_id: 1)
Room.find_or_create_by(token: "UVWXY15", name: "Quick decision15", location_id: 1)
Room.find_or_create_by(token: "BCDEF15", name: "Room115", location_id: 1)
Room.find_or_create_by(token: "FGHIJ15", name: "Room215", location_id: 1)
Room.find_or_create_by(token: "JKLMN15", name: "Room315", location_id: 1)
Room.find_or_create_by(token: "NOPQR15", name: "Room415", location_id: 1)
Room.find_or_create_by(token: "ABCDE25", name: "Manzanita Floor 1 Decision25", location_id: 1)
Room.find_or_create_by(token: "EFGHI25", name: "Take decision25", location_id: 1)
Room.find_or_create_by(token: "IJKLM25", name: "Food hangout25", location_id: 1)
Room.find_or_create_by(token: "MNOPQ25", name: "Let's party25", location_id: 1)
Room.find_or_create_by(token: "QRSTU25", name: "Where to go?25", location_id: 1)
Room.find_or_create_by(token: "UVWXY25", name: "Quick decision25", location_id: 1)
Room.find_or_create_by(token: "BCDEF25", name: "Room125", location_id: 1)
Room.find_or_create_by(token: "FGHIJ25", name: "Room225", location_id: 1)
Room.find_or_create_by(token: "JKLMN25", name: "Room235", location_id: 1)
Room.find_or_create_by(token: "NOPQR25", name: "Room425", location_id: 1)
Room.find_or_create_by(token: "ABCDE35", name: "Manzanita Floor 1 Decision35", location_id: 1)
Room.find_or_create_by(token: "EFGHI35", name: "Take decision35", location_id: 1)
Room.find_or_create_by(token: "IJKLM35", name: "Food hangout35", location_id: 1)
Room.find_or_create_by(token: "MNOPQ35", name: "Let's party35", location_id: 1)
Room.find_or_create_by(token: "QRSTU35", name: "Where to go?35", location_id: 1)
Room.find_or_create_by(token: "UVWXY35", name: "Quick decision35", location_id: 1)
Room.find_or_create_by(token: "BCDEF35", name: "Room135", location_id: 1)
Room.find_or_create_by(token: "FGHIJ35", name: "Room235", location_id: 1)
Room.find_or_create_by(token: "JKLMN35", name: "Room335", location_id: 1)
Room.find_or_create_by(token: "NOPQR35", name: "Room435", location_id: 1)
Room.find_or_create_by(token: "ABCDE45", name: "Manzanita Floor 1 Decision45", location_id: 1)
Room.find_or_create_by(token: "EFGHI45", name: "Take decision45", location_id: 1)
Room.find_or_create_by(token: "IJKLM45", name: "Food hangout45", location_id: 1)
Room.find_or_create_by(token: "MNOPQ45", name: "Let's party45", location_id: 1)
Room.find_or_create_by(token: "QRSTU45", name: "Where to go?45", location_id: 1)
Room.find_or_create_by(token: "UVWXY45", name: "Quick decision45", location_id: 1)
Room.find_or_create_by(token: "BCDEF45", name: "Room145", location_id: 1)
Room.find_or_create_by(token: "FGHIJ45", name: "Room245", location_id: 1)
Room.find_or_create_by(token: "JKLMN45", name: "Room345", location_id: 1)
Room.find_or_create_by(token: "NOPQR45", name: "Room445", location_id: 1)

Member.find_or_create_by(room_id: 1, user_id: 1, is_host: false)
Member.find_or_create_by(room_id: 1, user_id: 2, is_host: false)
Member.find_or_create_by(room_id: 1, user_id: 3, votes:"7;8;9;10;11", is_host: true)
Member.find_or_create_by(room_id: 2, user_id: 1, is_host: true)
Member.find_or_create_by(room_id: 2, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 3, user_id: 3, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 3, user_id: 1, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 3, user_id: 2, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 4, user_id: 3, votes:"4;5;8;2", is_host: false)
Member.find_or_create_by(room_id: 4, user_id: 2, votes:"5;8;2", is_host: false)
Member.find_or_create_by(room_id: 4, user_id: 1, votes:"4;8;2", is_host: true)
Member.find_or_create_by(room_id: 4, user_id: 4, votes:"4;5;8", is_host: false)
Member.find_or_create_by(room_id: 4, user_id: 5,  is_host: false)
Member.find_or_create_by(room_id: 5, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 5, user_id: 4, votes:"1;2;14", is_host: false)
Member.find_or_create_by(room_id: 5, user_id: 2, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 5, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 6, user_id: 1, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 6, user_id: 2, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 6, user_id: 3, votes:"11;12;13;3;4;6;7", is_host: false)
Member.find_or_create_by(room_id: 6, user_id: 4, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 7, user_id: 3, votes:"1;2;3;5;6;7;8;9;10", is_host: false)
Member.find_or_create_by(room_id: 7, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 7, user_id: 2, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 7, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 8, user_id: 3, votes:"9;10;11;12;8;1;2", is_host: false)
Member.find_or_create_by(room_id: 8, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 8, user_id: 2, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 8, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 9, user_id: 3, votes:"7;5;1;6;9;10;14", is_host: false)
Member.find_or_create_by(room_id: 9, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 9, user_id: 2, votes:"1;2;3;10;14", is_host: true)
Member.find_or_create_by(room_id: 9, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 10, user_id: 3, votes:"1;2;3", is_host: true)
Member.find_or_create_by(room_id: 10, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 10, user_id: 2, votes:"1;2;3;14;11", is_host: false)
Member.find_or_create_by(room_id: 10, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 11, user_id: 3, is_host: true)
Member.find_or_create_by(room_id: 12, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 13, user_id: 3, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 14, user_id: 3, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 15, user_id: 3, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 16, user_id: 3, votes:"4;5;8;2", is_host: false)
Member.find_or_create_by(room_id: 17, user_id: 3, votes:"5;8;2", is_host: false)
Member.find_or_create_by(room_id: 18, user_id: 3, votes:"4;8;2", is_host: true)
Member.find_or_create_by(room_id: 19, user_id: 3, votes:"4;5;8", is_host: false)
Member.find_or_create_by(room_id: 20, user_id: 3,  is_host: false)
Member.find_or_create_by(room_id: 21, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 22, user_id: 3, votes:"1;2;14", is_host: false)
Member.find_or_create_by(room_id: 23, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 24, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 25, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 26, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 27, user_id: 3, votes:"11;12;13;3;4;6;7", is_host: false)
Member.find_or_create_by(room_id: 28, user_id: 3, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 29, user_id: 3, votes:"1;2;3;5;6;7;8;9;10", is_host: false)
Member.find_or_create_by(room_id: 30, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 31, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 32, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 33, user_id: 3, votes:"9;10;11;12;8;1;2", is_host: false)
Member.find_or_create_by(room_id: 34, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 35, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 36, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 37, user_id: 3, votes:"7;5;1;6;9;10;14", is_host: false)
Member.find_or_create_by(room_id: 38, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 39, user_id: 3, votes:"1;2;3;10;14", is_host: true)
Member.find_or_create_by(room_id: 40, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 41, user_id: 3, votes:"1;2;3", is_host: true)
Member.find_or_create_by(room_id: 42, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 43, user_id: 3, votes:"1;2;3;14;11", is_host: false)
Member.find_or_create_by(room_id: 44, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 45, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 46, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 47, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 48, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 49, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 50, user_id: 3, is_host: false)

Member.find_or_create_by(room_id: 51, user_id: 3, votes:"1;2;3", is_host: true)
Member.find_or_create_by(room_id: 52, user_id: 4, is_host: false)
Member.find_or_create_by(room_id: 53, user_id: 2, votes:"1;2;3;14;11", is_host: false)
Member.find_or_create_by(room_id: 54, user_id: 5, is_host: false)
Member.find_or_create_by(room_id: 55, user_id: 3, is_host: true)
Member.find_or_create_by(room_id: 56, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 57, user_id: 3, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 58, user_id: 3, votes:"11;12;13", is_host: false)
Member.find_or_create_by(room_id: 59, user_id: 3, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 60, user_id: 3, votes:"4;5;8;2", is_host: false)
Member.find_or_create_by(room_id: 61, user_id: 3, votes:"5;8;2", is_host: false)
Member.find_or_create_by(room_id: 62, user_id: 3, votes:"4;8;2", is_host: true)
Member.find_or_create_by(room_id: 63, user_id: 3, votes:"4;5;8", is_host: false)
Member.find_or_create_by(room_id: 64, user_id: 3,  is_host: false)
Member.find_or_create_by(room_id: 65, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 66, user_id: 3, votes:"1;2;14", is_host: false)
Member.find_or_create_by(room_id: 67, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 68, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 69, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 70, user_id: 3, votes:"1;2;3", is_host: false)
Member.find_or_create_by(room_id: 71, user_id: 3, votes:"11;12;13;3;4;6;7", is_host: false)
Member.find_or_create_by(room_id: 72, user_id: 3, votes:"11;12;13", is_host: true)
Member.find_or_create_by(room_id: 73, user_id: 3, votes:"1;2;3;5;6;7;8;9;10", is_host: false)
Member.find_or_create_by(room_id: 74, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 75, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 76, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 77, user_id: 3, votes:"9;10;11;12;8;1;2", is_host: false)
Member.find_or_create_by(room_id: 78, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 79, user_id: 3, votes:"1;2;3;10;11", is_host: true)
Member.find_or_create_by(room_id: 80, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 81, user_id: 3, votes:"7;5;1;6;9;10;14", is_host: false)
Member.find_or_create_by(room_id: 82, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 83, user_id: 3, votes:"1;2;3;10;14", is_host: true)
Member.find_or_create_by(room_id: 84, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 85, user_id: 3, votes:"1;2;3", is_host: true)
Member.find_or_create_by(room_id: 86, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 87, user_id: 3, votes:"1;2;3;14;11", is_host: false)
Member.find_or_create_by(room_id: 88, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 89, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 90, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 91, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 92, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 93, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 94, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 95, user_id: 3, votes:"1;2;3", is_host: true)
Member.find_or_create_by(room_id: 96, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 97, user_id: 3, votes:"1;2;3;14;11", is_host: false)
Member.find_or_create_by(room_id: 98, user_id: 3, votes:"1;2;3", is_host: true)
Member.find_or_create_by(room_id: 99, user_id: 3, is_host: false)
Member.find_or_create_by(room_id: 100, user_id: 3, votes:"1;2;3;14;11", is_host: false)

Restaurant.find_or_create_by(name: "Deja Vu", location_id: 1, description: "Indian food")
Restaurant.find_or_create_by(name: "Freebirds", location_id: 1, description: "Burritos")
Restaurant.find_or_create_by(name: "Woodstock's Pizza", location_id: 1, description: "Pizza")
Restaurant.find_or_create_by(name: "South Coast Deli", location_id: 1, description: "Sandwiches")
Restaurant.find_or_create_by(name: "Naan Stop", location_id: 1, description: "Indian food")
Restaurant.find_or_create_by(name: "Hanna Kitchen", location_id: 1, description: "Asian fusion")
Restaurant.find_or_create_by(name: "The Habit", location_id: 1, description: "SB Burgers")
Restaurant.find_or_create_by(name: "Super Cuca's", location_id: 1, description: "Mexican Burgers")
Restaurant.find_or_create_by(name: "Buddha Bowls", location_id: 1, description: "Bread Bowls")
Restaurant.find_or_create_by(name: "Poke Ceviche", location_id: 1, description: "Poke and Wraps")
Restaurant.find_or_create_by(name: "Spudnuts", location_id: 1, description: "Donuts")
Restaurant.find_or_create_by(name: "Caje", location_id: 1, description: "Hip Coffee Shop")
Restaurant.find_or_create_by(name: "Lao Wang", location_id: 1, description: "Asian food")
Restaurant.find_or_create_by(name: "Shushiya", location_id: 1, description: "Shushi place")


#Restaurants random generation
@n = 1000
charset = Array('A'..'Z') + Array('a'..'z')

restaurants = []
for i in 1..@n.to_i do
    @location = rand(1..3)
    @name = "RandName"+ Array.new(10) { charset.sample }.join
    @desc = "RandDesc"+ Array.new(42) { charset.sample }.join
    restaurants << {name: @name, description:@desc, location_id:@location}
end
Restaurant.create(restaurants)


# Todo: @Wei-Yee clean up this when you merge
rooms = []
for i in 100..200 do
    rooms << {token: i.to_s, name: "EMPTY ROOM", location_id: 1}
end
Room.create(rooms)

users = []
for i in 0..1000 do
    users << {name: "FAKE USER", username: i.to_s, password: 'password', is_auth: true}
end
User.create(users)

members = []
for i in 0..1000 do
    members << {room_id: rand(900)+11, user_id: i+1, votes:"11;12;13", is_host: false}
end
Member.create(members)
